import styles from "@/styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { data, status, update } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <p>
            <b>Data</b>:{JSON.stringify(data)}
          </p>
          <p>
            <b>Status</b>:{JSON.stringify(status)}
          </p>
          <p>
            <b>Update</b>:{JSON.stringify(update)}
          </p>
        </div>
        <div>
          <button onClick={() => signIn()}>Sign In</button>
          <button onClick={() => signOut()}>Sign Out</button>
        </div>
      </main>
    </>
  );
}
