import styles from "@/styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { data, status, update } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <pre>Data:{JSON.stringify(data)}</pre>
          <pre>Status:{JSON.stringify(status)}</pre>
          <pre>Update:{JSON.stringify(update)}</pre>
        </div>
        <div>
          <button onClick={() => signIn()}>Sign In</button>
          <button onClick={() => signOut()}>Sign Out</button>
        </div>
      </main>
    </>
  );
}
